### ISSUE TITLE
Export proper Glossarist dataset that can be read by Geolexica

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/termium#3]
As per: https://github.com/glossarist/glossarist-ruby/issues/83#issuecomment-1816447057 by @HassanAkbar 

> we need 2 folders for creating a concept dataset (both folder names are singular)
> 
> * concept
> * localized_concept

In this gem, we have a `Cli#convert` method that converts a Termium dataset into Glossarist.

However, the files generated do not show this structure. Instead, it is the older structure where the "concept" and "localized concept" are within the same YAML file:

https://github.com/glossarist/termium/blob/4b7ce29a7e0199f9766d0027cd081441fd9e2f97/lib/termium/cli.rb#L52-L58

`sources/concepts` in iso-iec-2382 repo ([link](https://github.com/metanorma/iso-iec-2382/tree/main/sources/concepts)):
```
concept-10031778.yaml
concept-10031781.yaml
concept-2120533.yaml
concept-2120534.yaml
...
```

`concept-2120533.yaml`:
```yaml
---
termid: '2120533'
term: network
eng:
  id: '2120533'
  terms:
  - type: expression
  # ...
  definition:
  - content: arrangement of entities and their interconnections
  # ...
fre:
  id: '2120533'
  terms:
  - type: expression
  # ...
```

This task is to update the following method so that it exports a Glossarist dataset that is immediately useable by Geolexica:
https://github.com/glossarist/termium/blob/4b7ce29a7e0199f9766d0027cd081441fd9e2f97/lib/termium/cli.rb#L58
